In [2]:
import torch

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[     0.1398,      0.0000, -23061.5000],
        [     0.0000,      0.0000,      0.0000],
        [     0.0000,      0.0000, -30411.6875],
        [     0.0000, -23075.1250,      0.0000],
        [     0.0000,      0.0000,      0.0000]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5186, 0.0722, 0.0088],
        [0.9226, 0.0562, 0.0382],
        [0.3118, 0.4527, 0.2696],
        [0.3498, 0.4156, 0.0260],
        [0.6140, 0.6066, 0.6081]])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)   

tensor([[ 0.7073, -0.5690,  2.1870],
        [ 0.3608,  3.0796, -0.2846],
        [-0.5301, -0.1651,  0.8399],
        [-0.2410, -0.8154,  1.0418],
        [-0.4727, -0.5543,  0.4802]])


In [10]:
y = torch.rand(5, 3)
y

tensor([[0.5392, 0.1986, 0.8741],
        [0.1968, 0.6535, 0.8330],
        [0.2383, 0.1106, 0.1276],
        [0.7388, 0.2717, 0.0682],
        [0.7260, 0.0866, 0.4962]])

In [11]:
x.add_(y)

tensor([[ 1.2465, -0.3704,  3.0610],
        [ 0.5576,  3.7331,  0.5483],
        [-0.2918, -0.0545,  0.9675],
        [ 0.4978, -0.5437,  1.1100],
        [ 0.2533, -0.4677,  0.9764]])

In [13]:
x

tensor([[ 1.2465, -0.3704,  3.0610],
        [ 0.5576,  3.7331,  0.5483],
        [-0.2918, -0.0545,  0.9675],
        [ 0.4978, -0.5437,  1.1100],
        [ 0.2533, -0.4677,  0.9764]])

In [19]:
result = torch.empty(5,3)
result

tensor([[0.1398, 0.0000, 0.1398],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [20]:
torch.add(x,y, out=result)

tensor([[ 1.7857, -0.1718,  3.9351],
        [ 0.7545,  4.3865,  1.3813],
        [-0.0534,  0.0561,  1.0951],
        [ 1.2366, -0.2720,  1.1782],
        [ 0.9793, -0.3810,  1.4726]])

In [21]:
result

tensor([[ 1.7857, -0.1718,  3.9351],
        [ 0.7545,  4.3865,  1.3813],
        [-0.0534,  0.0561,  1.0951],
        [ 1.2366, -0.2720,  1.1782],
        [ 0.9793, -0.3810,  1.4726]])

In [22]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [27]:
x[0,0]

tensor(0.2293)

In [28]:
x[0,0].item()

0.22934465110301971